name: Feature Request
description: Suggest an idea
title: '[S] title'
assignees: afkvido,donaldli2020
labels: Enhancement, Open
body:

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: |
        A clear and concise description of what you would like.
        Please provide as much information as possible.
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date of submittion
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a bug report
      options:
        - label: |
            This feature wasn't already requested.
            (I have checked every feature request on GitHub)
          required: true
        - label: |
            I agree to this repository's prerequisites.
            (I have read and agree to the License, Code of Conduct, and Contributing Guidelines)
          required: true
